name: company_printer
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  print_bluetooth_thermal: ^1.0.8
  permission_handler: ^11.3.1
  esc_pos_utils_plus: ^2.0.4
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  screenshot: ^3.0.0
  image: ^4.1.3
  http: ^1.4.0
  path_provider: ^2.1.2
  flutter_bluetooth_printer: ^2.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/printer.png" 
  android: true
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/printer.png
